---
- hosts: Azure
  vars:
    ansible_site_path: "c:\\inetpub\\wwwroot\\ansibletest"
  tasks:
  - name: create staging path
    win_file: path={{ ansible_site_path }} state=directory
    
  - name: create new website
    win_iis_website:
      name: "Ansible Test Site"
      state: started
      port: 1234
      physical_path: "{{ ansible_site_path }}"
  - name: Open site's port on firewall
    win_firewall_rule:
      name: mysite1234
      enable: yes
      state: present
      localport: 1234
      action: Allow
      direction: In
      protocol: Tcp
      force: true
    tags: firewall
  - name: default-website-index
    win_copy:
      src: files/index.html
      dest: "C:\\inetpub\\wwwroot\\ansibletest\\index.html"
