---
- name : "Create VM"
  connection: local
  hosts: all
  tasks:
   - name: Create a resource group
     azure_rm_resourcegroup:
       name: Akp-VM-Test
       location: eastus

   - name: Create virtual network
     azure_rm_virtualnetwork:
        resource_group: Akp-VM-Test
        name: testvn001
        address_prefixes: "10.10.0.0/16"

   - name: Add subnet
     azure_rm_subnet:
        resource_group: Akp-VM-Test
        name: subnet001
        address_prefix: "10.10.0.0/24"
        virtual_network: testvn001

   - name: Create public ip
     azure_rm_publicipaddress:
         resource_group: Akp-VM-Test
         allocation_method: Static
         name: publicip001

   - name: Create security group that allows SSH
     azure_rm_securitygroup:
         resource_group: Akp-VM-Test
         name: secgroup001
         rules:
           - name: SSH
             protocol: Tcp
             destination_port_range: 22
             access: Allow
             priority: 101
             
   - name: Create security group that allows SSH
     azure_rm_securitygroup:
         resource_group: Akp-VM-Test
         name: secgroup001
         rules:
           - name: SSH
             protocol: Tcp
             destination_port_range: 22
             access: Allow
             priority: 101
             direction: Inbound

   - name: Create NIC
     azure_rm_networkinterface:
          resource_group: Akp-VM-Test
          name: testnic001
          virtual_network: testvn001
          subnet: subnet001
          public_ip_name: publicip001
          security_group: secgroup001
          
   - name: Create VM with defaults
     azure_rm_virtualmachine:
       resource_group: Akp-VM-Test
       name: Akp-VM-Test-Ubuntu
       location: eastus
       vm_size: Standard_B1s
       admin_username: akpadmin
       admin_password: AkpAzureLinux@123
       managed_disk_type: Standard_LRS
       os_disk_size_gb: 64
       network_interfaces: testnic001
       image:
         offer: UbuntuServer
         publisher: Canonical
         sku: '18.04-LTS'
         version: latest

