---
- name : "Create VM"
  connection: local
  hosts: all
  vars:
     ansible_python_interpreter: /usr/bin/python3.6
  tasks:
   - name: Create a resource group
     azure_rm_resourcegroup:
       name: Akp-RG-Test
       location: eastus
